# SPDX-FileCopyrightText: Chris Wilson <christopher.david.wilson@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

---
extends: default

ignore-from-file: .gitignore

rules:
  braces:
    forbid: non-empty
  brackets:
    forbid: non-empty
  comments:
    level: warning
    min-spaces-from-content: 1 # needed for compatibility with Prettier
  float-values:
    require-numeral-before-decimal: true
  indentation:
    spaces: 2 # must match indent_size in .editorconfig file
  line-length:
    allow-non-breakable-inline-mappings: true
  quoted-strings:
    required: only-when-needed
    allow-quoted-quotes: true
    quote-type: double
