# SPDX-FileCopyrightText: Chris Wilson <christopher.david.wilson@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Docs (Dev)

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: docs-deploy

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  build-and-publish:
    name: Build and Publish Docs
    if: github.repository_owner == 'tinydantic'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # https://github.com/actions/checkout/issues/249
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          python-version: "3.12"
      - name: Configure Git for GitHub Actions bot
        # yamllint disable rule:line-length
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        # yamllint enable rule:line-length
      - name: Build documentation
        run: uv run --group docs poe docs-build
      - name: Commit documentation
        run: uv run --group docs poe docs-ci-publish dev
      - name: Set dev as the default version
        run: uv run --group docs poe docs-ci-set-default dev
      - name: Create archive
        run: git archive -o site.zip gh-pages
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: documentation
          path: site.zip
