# SPDX-FileCopyrightText: Chris Wilson <christopher.david.wilson@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

---
name: Docs (Release)

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

concurrency:
  group: docs-deploy

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  build-and-publish:
    name: Build and Publish Docs
    if: github.repository_owner == 'tinydantic'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # https://github.com/actions/checkout/issues/249
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          python-version: "3.12"
      - name: Configure Git for GitHub Actions bot
        # yamllint disable rule:line-length
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        # yamllint enable rule:line-length
      - name: Build documentation
        run: uv run --group docs poe docs-build
      - name: Get doc version
        run: |
          TAG_NAME=${{ github.ref_name }}
          DOC_VERSION=${TAG_NAME#v}
          echo "Documentation version: $DOC_VERSION"
          echo "DOC_VERSION=$DOC_VERSION" >> $GITHUB_ENV
      - name: Commit documentation
        run: >-
          uv run --group docs poe docs-ci-publish "$DOC_VERSION" latest
      - name: Create archive
        run: git archive -o site.zip gh-pages
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: documentation
          path: site.zip
